Alinawayne
skillup-aqa/theme3-java pull request #5
Opened 2024-03-09 07:38 UTC by alina-wayne

Java homework 3.9.2024 - AW

2024-03-11 22:08 UTC, vikmaksymenko requested changes
Давайте коментарям до комітів осмислені назви, інакше складно буде зрозуміти, що і в якому ви робили, перш за все вам самій за тиждень-два 
![image](https://github.com/skillup-aqa/theme3-java/assets/5682824/bb61a188-26c7-469f-88e4-d0fb3d293899)

2024-03-11 22:15 UTC, vikmaksymenko requested changes

2024-03-11 22:15 UTC, vikmaksymenko commented on src/main/java/part1/ArithmeticMeanCalculator.java
> +        // Calculate the mean
Коментарі до коду - це чудово, але тут назва дає достатньо контексту. Плюс якщо ви описуєте метод чи клас, краще користуватися [ Java Doc ](https://www.baeldung.com/javadoc)

2024-03-11 22:15 UTC, vikmaksymenko commented on src/main/java/part1/ArithmeticMeanCalculator.java
> +        int a = 1;
А чому `a` став `int`?

2024-03-11 22:15 UTC, vikmaksymenko commented on src/main/java/part1/CelsiusToFahrenheitConvertor.java
> +     double fahrenheit = (celsius * 9/5) +32;
Підправте форматування 
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#formatter-in-settings

2024-03-11 22:15 UTC, vikmaksymenko commented on src/main/java/part1/CelsiusToFahrenheitConvertor.java
> +    public static double celsiusToFahrenheitConvertor(double celsius) {
А чому ви змінили назву методу?

2024-03-11 22:15 UTC, vikmaksymenko commented on src/main/java/part1/HoursToMinutesConvertor.java
> -}
Думаю, ви дарма видалили цей файл, поверніть його і перенесіть рішення з 'HoursToMinutesAndSecondsConverter '

2024-03-11 22:15 UTC, vikmaksymenko commented on src/main/java/part1/PercentCalculator.java
> +        double percentage = (value / total) * 100;
Перенесіть будь-ласка рішення в метод 'calculatePercent'

2024-03-11 22:15 UTC, vikmaksymenko commented on src/test/java/part1/HoursToMinutesConvertorAndSecondsTest.java
> -
Цей код ви також дарма видалили

2024-03-11 22:15 UTC, vikmaksymenko commented on src/main/java/part1/SalaryCalculator.java
> +    double resultSalaty = Math.round(calculateSalaryAfterTaxes - ESV);
Перенесіть цей код в відповідні методи

2024-03-18 03:01 UTC, alina-wayne commented
Implementing changes for homework java-3

2024-03-18 05:12 UTC, closed without merging